version: 2
updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
          time: '12:00'
      open-pull-requests-limit: 10
      labels:
          - dependencies
      commit-message:
          prefix: chore
          prefix-development: chore
          include: scope
