version = 1

[merge]
automerge_label = "dependencies"
method = "squash"
delete_branch_on_merge = true

[merge.message]
title = "pull_request_title"
strip_html_comments = true

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

[approve]
auto_approve_usernames = ["dependabot"]
